name: flutter_template
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  build_runner: ^1.11.1
  cached_network_image: ^2.5.0
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  flutter_svg: ^0.19.2+1
  fluttertoast: ^7.1.8
  freezed: ^0.12.7
  google_fonts: ^1.1.2
  injectable: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  injectable_generator: ^1.0.7
  lint: ^1.5.1

flutter:
  uses-material-design: true

assets:
  - assets/
